### PR TITLE
Directionality Support

### PR DESCRIPTION
**Pull request by takifouhal**
- added directionality dynamic variants and utils
- replaced Alignment with AlignmentGeometry to allow other implementers (AlignmentDirectional)

### CODE REVIEW

**Comment by bdlukaa** [comment]
`EdgeInsets` should be `EdgeInsetsDirectional`

**Comment by takifouhal** [comment]
@bdlukaa 
I've just added support to EdgeInsets, BorderRadius and Border.
if there is anything else that I've missed please let me know.
thanks.

**Comment by bdlukaa** [comment]
Could a few tests be added to confirm the stability of the PR?

**Comment by leoafarias** [comment]
merging as we have to deploy the refactor

**Pull request merged**
